### PR TITLE
Fix slider on first/last slide

### PR DESCRIPTION
**Pull request by marcwieland95**
While on type slider and on first/last slide. Arrow is disabled, but
autoplay and keyboard still works.

### CODE REVIEW

**Comment by jedrzejchalubek** [comment]
I really don't like the idea of stopping autoplay in slider type on first/last slides. If someone setup autoplay he don't expecting this.

On the other hand the `Run.flag` with true value means, that we need to make offset animation. There is no offset animation in slider type, so setting this up will do nothing (this variable is not used).

Keyboard bug need to be fixed.

**Comment by marcwieland95** [comment]
In slider there shouldn't be a possibility to loop, for this we have carousel. So autoplay should stop at the last slide. On the first slide I just reset autolay, because there's sometimes a ugly behaviour.

In my if-statement there is nothing to do, but an empty one is also ugly.

**Comment by jedrzejchalubek** [comment]
I will wait with this, maybe someone else will say what thinks on "how this should behave".

**Comment by jedrzejchalubek** [comment]
Version 3.0.0 is coming. Feature requests for version 2.0 are suspended. Closing, sorry.

**Pull request closed without merging**
